// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sast")>]
[<assembly: AssemblyProductAttribute("Sast")>]
[<assembly: AssemblyDescriptionAttribute("F# generative type provider providing an implementation of session types")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sast"
    let [<Literal>] AssemblyProduct = "Sast"
    let [<Literal>] AssemblyDescription = "F# generative type provider providing an implementation of session types"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
